name: Create Release Assets

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows-exe:
    name: Package Windows Application (for Windows 7)
    runs-on: windows-2019
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python for Windows 7 compatibility
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install requests PyQt5 cryptography pyinstaller

      - name: Build application with PyInstaller
        run: >
          pyinstaller
          --name NeteaseMusicDownloader
          --onefile
          --windowed
          --icon=163.ico
          unetease_music_ui.py

      - name: Upload .exe to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release upload
          ${{ github.ref_name }}
          dist/NeteaseMusicDownloader.exe

  build-and-push-ghcr:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./163_music_download_docker
          file: ./163_music_download_docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}